// Code generated by MockGen. DO NOT EDIT.
// Source: currency.go

// Package mock_view is a generated GoMock package.
package mock_view

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCurrencier is a mock of Currencier interface.
type MockCurrencier struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencierMockRecorder
}

// MockCurrencierMockRecorder is the mock recorder for MockCurrencier.
type MockCurrencierMockRecorder struct {
	mock *MockCurrencier
}

// NewMockCurrencier creates a new mock instance.
func NewMockCurrencier(ctrl *gomock.Controller) *MockCurrencier {
	mock := &MockCurrencier{ctrl: ctrl}
	mock.recorder = &MockCurrencierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencier) EXPECT() *MockCurrencierMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCurrencier) Get() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCurrencierMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCurrencier)(nil).Get))
}
